name: CICD

on:
  push:
    branches: [ trials-devops ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging 

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Setup Node để chạy test
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies trong thư mục application
      - name: Install dependencies
        run: npm install
        working-directory: application-example

      # Run tests
      - name: Run tests
        run: npm test
        working-directory: application-example

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_Region }}

      # Login ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      # Build & Push Docker image
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -f ./infrastructure/Dockerfile \
            -t $ECR_REGISTRY/aiclipx/${{ secrets.ENV }}:${{ github.sha }} \
            application-example

          docker push $ECR_REGISTRY/aiclipx/${{ secrets.ENV }}:${{ github.sha }}

          echo "image=$ECR_REGISTRY/aiclipx/${{ secrets.ENV }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      # Render ECS task definition
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: infrastructure/nodejs-app-task-definition.json
          container-name: aiclipx-${{ secrets.Env }}
          image: ${{ steps.build-image.outputs.image }}

      # Deploy ECS
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.Env }}-v1
          cluster: aiclipx-${{ secrets.Env }}
          wait-for-service-stability: true
